name: pr-validate
displayName: PR验收-registry
triggers:
  pr:
    branches:
      precise:
        - master
        - main
stages:
  - stage:
      name: validate
      displayName: 验收 index.json
      failFast: true
      steps:
        - step: build@node
          name: validate
          displayName: node scripts/registry.mjs validate
          inputs:
            nodeVersion: '18.15.0'
          commands:
            - node scripts/registry.mjs validate
